global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'asr-translator-api'
    metrics_path: /metrics/
    scrape_interval: 5s
    static_configs:
      - targets: ['web:8000']
    basic_auth:
      username: 'prometheus'
      password: "${METRICS_TOKEN}"

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15672']
    metrics_path: /api/metrics
    basic_auth:
      username: "${RABBITMQ_USER}"
      password: "${RABBITMQ_PASSWORD}"

  - job_name: 'postgres'
    static_configs:
      - targets: ['db:5432'] 